### ISSUE TITLE
Error on pixel drawing with Valetudo 0.5.2

### ISSUE THREAD

**Issue by Poeschl** [Hypfer/ICantBelieveItsNotValetudo#24]
When the robot sends new map data the application crashes. Didn't occurs on firmware 0.5.1

I installed a clean firmware with valetudo 0.5.2 and configured MQTT.
The version of ICantBelieveItsNotValetudo is 3cf4f8a

Full log: 
```
> i-cant-believe-its-not-valetudo@0.2.0 start /app
> node app.js
Loading configuration file: /app/config.json
Connecting to MQTT Broker
Webserver running on port 3000
Connected to MQTT Broker
/app/node_modules/@jimp/utils/dist/index.js:42
  throw error;
  ^
Error: hex, x and y must be numbers
    at Jimp.throwError (/app/node_modules/@jimp/utils/dist/index.js:35:13)
    at Jimp.setPixelColor (/app/node_modules/@jimp/core/dist/index.js:903:111)
    at drawPixel (/app/lib/Tools.js:83:35)
    at Array.forEach (<anonymous>)
    at /app/lib/Tools.js:81:61
    at Array.forEach (<anonymous>)
    at Jimp.<anonymous> (/app/lib/Tools.js:78:65)
    at Timeout._onTimeout (/app/node_modules/@jimp/core/dist/index.js:354:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.2.0 start: `node app.js`
npm ERR! Exit status 1
```

The mqtt data from my robot (its cut after 20000 chars):
```
{"header_length":20,"data_length":136728,"version":{"major":1,"minor":1},"map_index":981,"map_sequence":66,"image":{"segments":{"count":6},"pixels":{"floor":[[147,259],[148,259],[149,259],[150,259],[151,259],[152,259],[153,259],[154,259],[147,258],[148,258],[149,258],[150,258],[151,258],[152,258],[153,258],[154,258],[181,258],[182,258],[183,258],[184,258],[185,258],[186,258],[187,258],[188,258],[189,258],[147,257],[148,257],[149,257],[150,257],[151,257],[152,257],[153,257],[154,257],[183,257],[185,257],[186,257],[187,257],[188,257],[189,257],[147,256],[148,256],[149,256],[150,256],[151,256],[152,256],[153,256],[154,256],[185,256],[186,256],[187,256],[188,256],[189,256],[147,255],[148,255],[149,255],[150,255],[151,255],[152,255],[153,255],[154,255],[155,255],[156,255],[157,255],[158,255],[159,255],[160,255],[161,255],[162,255],[163,255],[164,255],[165,255],[166,255],[167,255],[168,255],[169,255],[170,255],[171,255],[181,255],[182,255],[183,255],[184,255],[185,255],[186,255],[187,255],[188,255],[189,255],[147,254],[148,254],[149,254],[150,254],[151,254],[152,254],[153,254],[154,254],[155,254],[156,254],[157,254],[158,254],[159,254],[160,254],[161,254],[162,254],[163,254],[164,254],[165,254],[166,254],[167,254],[168,254],[169,254],[170,254],[171,254],[172,254],[173,254],[174,254],[175,254],[176,254],[177,254],[178,254],[179,254],[180,254],[181,254],[182,254],[183,254],[184,254],[185,254],[186,254],[187,254],[188,254],[189,254],[190,254],[191,254],[192,254],[193,254],[194,254],[195,254],[196,254],[197,254],[198,254],[199,254],[200,254],[201,254],[202,254],[203,254],[204,254],[205,254],[206,254],[207,254],[208,254],[209,254],[210,254],[211,254],[212,254],[213,254],[214,254],[146,253],[147,253],[148,253],[149,253],[150,253],[151,253],[152,253],[153,253],[154,253],[155,253],[156,253],[157,253],[158,253],[159,253],[160,253],[161,253],[162,253],[163,253],[164,253],[165,253],[166,253],[167,253],[168,253],[169,253],[170,253],[171,253],[172,253],[173,253],[174,253],[175,253],[176,253],[177,253],[178,253],[179,253],[180,253],[181,253],[182,253],[183,253],[184,253],[185,253],[186,253],[187,253],[188,253],[189,253],[190,253],[191,253],[192,253],[193,253],[194,253],[195,253],[196,253],[197,253],[198,253],[199,253],[200,253],[201,253],[202,253],[203,253],[204,253],[205,253],[206,253],[207,253],[208,253],[209,253],[210,253],[211,253],[212,253],[213,253],[214,253],[215,253],[216,253],[217,253],[218,253],[219,253],[142,252],[143,252],[144,252],[145,252],[146,252],[147,252],[148,252],[149,252],[150,252],[151,252],[152,252],[153,252],[154,252],[155,252],[156,252],[157,252],[158,252],[159,252],[160,252],[161,252],[162,252],[163,252],[164,252],[165,252],[166,252],[167,252],[168,252],[169,252],[170,252],[171,252],[172,252],[173,252],[174,252],[178,252],[179,252],[180,252],[181,252],[182,252],[183,252],[184,252],[185,252],[186,252],[187,252],[188,252],[189,252],[190,252],[191,252],[192,252],[193,252],[194,252],[195,252],[196,252],[197,252],[198,252],[199,252],[200,252],[201,252],[202,252],[203,252],[204,252],[205,252],[206,252],[207,252],[208,252],[209,252],[210,252],[211,252],[212,252],[213,252],[214,252],[215,252],[216,252],[217,252],[218,252],[219,252],[142,251],[143,251],[144,251],[145,251],[146,251],[147,251],[148,251],[149,251],[150,251],[151,251],[152,251],[153,251],[154,251],[155,251],[156,251],[157,251],[158,251],[159,251],[160,251],[161,251],[162,251],[163,251],[164,251],[165,251],[166,251],[167,251],[168,251],[169,251],[170,251],[171,251],[172,251],[173,251],[174,251],[178,251],[179,251],[180,251],[181,251],[182,251],[183,251],[184,251],[185,251],[186,251],[187,251],[188,251],[189,251],[190,251],[191,251],[196,251],[197,251],[198,251],[199,251],[200,251],[201,251],[202,251],[203,251],[204,251],[205,251],[206,251],[207,251],[208,251],[209,251],[210,251],[211,251],[212,251],[213,251],[214,251],[215,251],[216,251],[217,251],[218,251],[219,251],[142,250],[143,250],[144,250],[145,250],[146,250],[147,250],[148,250],[149,250],[150,250],[151,250],[152,250],[153,250],[154,250],[155,250],[156,250],[157,250],[158,250],[159,250],[160,250],[161,250],[162,250],[163,250],[164,250],[165,250],[166,250],[167,250],[168,250],[169,250],[170,250],[171,250],[172,250],[173,250],[174,250],[178,250],[179,250],[180,250],[181,250],[182,250],[183,250],[184,250],[185,250],[186,250],[187,250],[188,250],[189,250],[190,250],[191,250],[196,250],[197,250],[198,250],[199,250],[200,250],[201,250],[202,250],[203,250],[204,250],[205,250],[206,250],[207,250],[208,250],[209,250],[210,250],[211,250],[212,250],[213,250],[214,250],[215,250],[216,250],[217,250],[218,250],[219,250],[142,249],[143,249],[144,249],[145,249],[146,249],[147,249],[148,249],[149,249],[150,249],[151,249],[152,249],[153,249],[154,249],[155,249],[156,249],[157,249],[158,249],[159,249],[160,249],[161,249],[162,249],[163,249],[164,249],[165,249],[166,249],[167,249],[168,249],[169,249],[170,249],[171,249],[172,249],[173,249],[174,249],[175,249],[178,249],[179,249],[180,249],[181,249],[182,249],[183,249],[184,249],[185,249],[186,249],[187,249],[188,249],[189,249],[190,249],[191,249],[196,249],[197,249],[198,249],[199,249],[200,249],[201,249],[202,249],[203,249],[204,249],[205,249],[206,249],[207,249],[208,249],[209,249],[210,249],[211,249],[212,249],[213,249],[214,249],[215,249],[216,249],[217,249],[218,249],[219,249],[142,248],[143,248],[144,248],[145,248],[146,248],[147,248],[148,248],[149,248],[150,248],[151,248],[152,248],[153,248],[154,248],[155,248],[156,248],[157,248],[158,248],[159,248],[160,248],[161,248],[162,248],[163,248],[164,248],[165,248],[166,248],[167,248],[168,248],[169,248],[170,248],[171,248],[172,248],[173,248],[174,248],[175,248],[176,248],[177,248],[178,248],[179,248],[180,248],[181,248],[182,248],[183,248],[184,248],[185,248],[186,248],[187,248],[188,248],[189,248],[190,248],[191,248],[192,248],[193,248],[194,248],[195,248],[196,248],[197,248],[198,248],[199,248],[200,248],[201,248],[202,248],[203,248],[204,248],[205,248],[206,248],[207,248],[208,248],[209,248],[210,248],[211,248],[212,248],[213,248],[214,248],[215,248],[216,248],[217,248],[218,248],[219,248],[142,247],[143,247],[144,247],[145,247],[146,247],[147,247],[148,247],[149,247],[150,247],[151,247],[152,247],[153,247],[154,247],[155,247],[156,247],[157,247],[158,247],[159,247],[160,247],[161,247],[162,247],[163,247],[164,247],[165,247],[166,247],[167,247],[168,247],[169,247],[170,247],[171,247],[172,247],[173,247],[174,247],[175,247],[176,247],[177,247],[178,247],[179,247],[180,247],[181,247],[182,247],[183,247],[184,247],[185,247],[186,247],[187,247],[188,247],[189,247],[190,247],[191,247],[192,247],[193,247],[194,247],[195,247],[196,247],[197,247],[198,247],[199,247],[200,247],[201,247],[202,247],[203,247],[204,247],[205,247],[206,247],[207,247],[208,247],[209,247],[210,247],[211,247],[212,247],[213,247],[214,247],[215,247],[216,247],[217,247],[218,247],[219,247],[142,246],[143,246],[144,246],[145,246],[146,246],[147,246],[148,246],[149,246],[150,246],[151,246],[152,246],[153,246],[154,246],[155,246],[156,246],[157,246],[158,246],[159,246],[160,246],[161,246],[162,246],[163,246],[164,246],[165,246],[166,246],[167,246],[168,246],[169,246],[170,246],[171,246],[172,246],[173,246],[174,246],[175,246],[176,246],[177,246],[178,246],[179,246],[180,246],[181,246],[182,246],[183,246],[184,246],[185,246],[186,246],[187,246],[188,246],[189,246],[190,246],[191,246],[192,246],[193,246],[194,246],[195,246],[196,246],[197,246],[198,246],[199,246],[200,246],[201,246],[202,246],[203,246],[204,246],[205,246],[206,246],[207,246],[208,246],[209,246],[210,246],[211,246],[212,246],[213,246],[214,246],[215,246],[216,246],[217,246],[218,246],[219,246],[142,245],[143,245],[144,245],[145,245],[146,245],[147,245],[148,245],[149,245],[150,245],[151,245],[152,245],[153,245],[154,245],[155,245],[156,245],[157,245],[158,245],[159,245],[160,245],[161,245],[162,245],[163,245],[164,245],[165,245],[166,245],[167,245],[168,245],[169,245],[170,245],[171,245],[172,245],[173,245],[174,245],[175,245],[176,245],[177,245],[178,245],[179,245],[180,245],[181,245],[182,245],[183,245],[184,245],[185,245],[186,245],[187,245],[188,245],[189,245],[190,245],[191,245],[192,245],[193,245],[194,245],[195,245],[196,245],[197,245],[198,245],[199,245],[200,245],[201,245],[202,245],[203,245],[204,245],[205,245],[206,245],[207,245],[208,245],[209,245],[210,245],[142,244],[143,244],[144,244],[145,244],[146,244],[147,244],[148,244],[149,244],[150,244],[151,244],[152,244],[153,244],[154,244],[155,244],[156,244],[157,244],[158,244],[159,244],[160,244],[161,244],[162,244],[163,244],[164,244],[165,244],[166,244],[167,244],[168,244],[169,244],[170,244],[171,244],[172,244],[173,244],[174,244],[175,244],[176,244],[177,244],[178,244],[179,244],[180,244],[181,244],[182,244],[183,244],[184,244],[185,244],[186,244],[187,244],[188,244],[194,244],[195,244],[196,244],[197,244],[198,244],[199,244],[200,244],[201,244],[202,244],[203,244],[204,244],[205,244],[206,244],[207,244],[208,244],[209,244],[210,244],[142,243],[143,243],[144,243],[145,243],[146,243],[147,243],[148,243],[149,243],[150,243],[151,243],[152,243],[153,243],[154,243],[155,243],[156,243],[157,243],[158,243],[159,243],[160,243],[161,243],[162,243],[163,243],[164,243],[165,243],[166,243],[167,243],[168,243],[169,243],[170,243],[171,243],[172,243],[173,243],[174,243],[175,243],[176,243],[177,243],[178,243],[179,243],[180,243],[181,243],[182,243],[183,243],[184,243],[185,243],[186,243],[187,243],[188,243],[190,243],[191,243],[198,243],[199,243],[200,243],[201,243],[202,243],[203,243],[204,243],[205,243],[206,243],[207,243],[208,243],[209,243],[210,243],[213,243],[214,243],[142,242],[143,242],[144,242],[145,242],[146,242],[147,242],[148,242],[149,242],[150,242],[151,242],[152,242],[153,242],[154,242],[155,242],[156,242],[157,242],[158,242],[159,242],[160,242],[161,242],[162,242],[163,242],[164,242],[165,242],[166,242],[167,242],[168,242],[169,242],[170,242],[171,242],[172,242],[173,242],[174,242],[175,242],[176,242],[177,242],[178,242],[179,242],[180,242],[181,242],[182,242],[183,242],[184,242],[185,242],[186,242],[187,242],[188,242],[189,242],[190,242],[191,242],[192,242],[193,242],[194,242],[195,242],[198,242],[199,242],[200,242],[201,242],[202,242],[203,242],[204,242],[205,242],[206,242],[207,242],[208,242],[209,242],[210,242],[212,242],[213,242],[142,241],[143,241],[144,241],[145,241],[146,241],[147,241],[148,241],[149,241],[150,241],[151,241],[152,241],[153,241],[154,241],[155,241],[156,241],[157,241],[158,241],[159,241],[160,241],[161,241],[162,241],[163,241],[164,241],[165,241],[166,241],[167,241],[168,241],[170,241],[171,241],[172,241],[173,241],[178,241],[179,241],[180,241],[181,241],[182,241],[183,241],[184,241],[185,241],[186,241],[187,241],[188,241],[189,241],[190,241],[191,241],[192,241],[193,241],[194,241],[195,241],[196,241],[197,241],[198,241],[199,241],[200,241],[201,241],[202,241],[203,241],[204,241],[205,241],[206,241],[207,241],[208,241],[209,241],[210,241],[212,241],[213,241],[142,240],[143,240],[144,240],[145,240],[146,240],[147,240],[148,240],[149,240],[150,240],[151,240],[152,240],[153,240],[154,240],[155,240],[156,240],[157,240],[158,240],[159,240],[160,240],[161,240],[162,240],[163,240],[164,240],[165,240],[166,240],[167,240],[178,240],[179,240],[180,240],[181,240],[182,240],[183,240],[184,240],[185,240],[186,240],[187,240],[188,240],[189,240],[190,240],[191,240],[192,240],[193,240],[194,240],[195,240],[196,240],[197,240],[198,240],[199,240],[200,240],[201,240],[202,240],[203,240],[204,240],[205,240],[206,240],[207,240],[208,240],[209,240],[210,240],[212,240],[213,240],[142,239],[143,239],[144,239],[145,239],[146,239],[147,239],[148,239],[149,239],[150,239],[151,239],[152,239],[153,239],[154,239],[155,239],[156,239],[157,239],[158,239],[159,239],[160,239],[161,239],[162,239],[163,239],[164,239],[165,239],[166,239],[167,239],[168,239],[169,239],[170,239],[171,239],[172,239],[173,239],[174,239],[175,239],[176,239],[177,239],[178,239],[179,239],[180,239],[181,239],[182,239],[183,239],[184,239],[185,239],[186,239],[187,239],[188,239],[189,239],[190,239],[191,239],[192,239],[193,239],[194,239],[195,239],[196,239],[197,239],[198,239],[199,239],[200,239],[201,239],[202,239],[203,239],[204,239],[205,239],[206,239],[207,239],[208,239],[209,239],[210,239],[142,238],[143,238],[144,238],[145,238],[146,238],[147,238],[148,238],[149,238],[150,238],[151,238],[152,238],[153,238],[154,238],[155,238],[156,238],[157,238],[158,238],[159,238],[160,238],[161,238],[162,238],[163,238],[164,238],[165,238],[166,238],[167,238],[168,238],[169,238],[170,238],[171,238],[172,238],[173,238],[174,238],[175,238],[176,238],[177,238],[178,238],[179,238],[180,238],[181,238],[182,238],[183,238],[184,238],[185,238],[186,238],[187,238],[188,238],[189,238],[190,238],[191,238],[192,238],[193,238],[194,238],[195,238],[196,238],[197,238],[198,238],[199,238],[200,238],[201,238],[202,238],[203,238],[204,238],[205,238],[206,238],[207,238],[208,238],[209,238],[210,238],[142,237],[143,237],[144,237],[145,237],[146,237],[147,237],[148,237],[149,237],[150,237],[151,237],[152,237],[153,237],[154,237],[155,237],[156,237],[157,237],[158,237],[159,237],[160,237],[161,237],[162,237],[163,237],[164,237],[165,237],[166,237],[167,237],[168,237],[169,237],[170,237],[171,237],[172,237],[173,237],[174,237],[175,237],[176,237],[177,237],[178,237],[179,237],[180,237],[181,237],[182,237],[183,237],[184,237],[185,237],[186,237],[187,237],[198,237],[199,237],[200,237],[201,237],[202,237],[203,237],[204,237],[205,237],[206,237],[207,237],[208,237],[209,237],[210,237],[142,236],[143,236],[144,236],[145,236],[146,236],[147,236],[148,236],[149,236],[150,236],[151,236],[152,236],[153,236],[154,236],[155,236],[156,236],[157,236],[158,236],[159,236],[160,236],[161,236],[162,236],[163,236],[164,236],[165,236],[166,236],[167,236],[168,236],[169,236],[170,236],[171,236],[172,236],[173,236],[174,236],[175,236],[176,236],[177,236],[178,236],[179,236],[180,236],[181,236],[182,236],[183,236],[184,236],[185,236],[186,236],[187,236],[198,236],[199,236],[200,236],[201,236],[202,236],[203,236],[204,236],[205,236],[206,236],[207,236],[208,236],[209,236],[210,236],[142,235],[143,235],[144,235],[145,235],[146,235],[147,235],[148,235],[149,235],[150,235],[151,235],[152,235],[153,235],[154,235],[155,235],[156,235],[157,235],[158,235],[159,235],[160,235],[161,235],[162,235],[163,235],[164,235],[165,235],[166,235],[167,235],[168,235],[169,235],[170,235],[171,235],[172,235],[173,235],[174,235],[175,235],[176,235],[177,235],[178,235],[179,235],[180,235],[181,235],[182,235],[183,235],[184,235],[185,235],[186,235],[187,235],[188,235],[189,235],[190,235],[191,235],[192,235],[193,235],[194,235],[195,235],[196,235],[197,235],[198,235],[199,235],[200,235],[201,235],[202,235],[203,235],[204,235],[205,235],[206,235],[207,235],[208,235],[209,235],[210,235],[142,234],[143,234],[144,234],[145,234],[146,234],[147,234],[148,234],[149,234],[150,234],[151,234],[152,234],[153,234],[154,234],[155,234],[156,234],[157,234],[158,234],[159,234],[160,234],[161,234],[162,234],[163,234],[164,234],[165,234],[166,234],[167,234],[174,234],[175,234],[176,234],[177,234],[178,234],[179,234],[180,234],[181,234],[182,234],[183,234],[184,234],[185,234],[186,234],[187,234],[188,234],[189,234],[190,234],[191,234],[192,234],[193,234],[194,234],[195,234],[196,234],[197,234],[198,234],[199,234],[200,234],[201,234],[202,234],[203,234],[204,234],[205,234],[206,234],[207,234],[208,234],[209,234],[210,234],[142,233],[143,233],[144,233],[145,233],[146,233],[147,233],[148,233],[149,233],[150,233],[151,233],[152,233],[153,233],[154,233],[155,233],[156,233],[157,233],[158,233],[159,233],[160,233],[161,233],[162,233],[163,233],[164,233],[165,233],[166,233],[167,233],[178,233],[179,233],[180,233],[181,233],[182,233],[183,233],[184,233],[185,233],[186,233],[187,233],[188,233],[189,233],[190,233],[191,233],[192,233],[193,233],[194,233],[195,233],[196,233],[197,233],[198,233],[199,233],[200,233],[201,233],[202,233],[203,233],[204,233],[205,233],[206,233],[207,233],[208,233],[209,233],[210,233],[142,232],[143,232],[144,232],[145,232],[146,232],[147,232],[148,232],[149,232],[150,232],[151,232],[152,232],[153,232],[154,232],[155,232],[156,232],[157,232],[158,232],[159,232],[160,232],[161,232],[162,232],[163,232],[164,232],[165,232],[166,232],[167,232],[168,232],[169,232],[170,232],[171,232],[172,232],[173,232],[174,232],[175,232],[177,232],[178,232],[179,232],[180,232],[181,232],[182,232],[183,232],[184,232],[185,232],[186,232],[187,232],[188,232],[189,232],[190,232],[191,232],[192,232],[193,232],[194,232],[195,232],[196,232],[197,232],[198,232],[199,232],[200,232],[201,232],[202,232],[203,232],[204,232],[205,232],[206,232],[207,232],[208,232],[209,232],[210,232],[142,231],[143,231],[144,231],[145,231],[146,231],[147,231],[148,231],[149,231],[150,231],[151,231],[152,231],[153,231],[154,231],[155,231],[156,231],[157,231],[158,231],[159,231],[160,231],[161,231],[162,231],[163,231],[164,231],[165,231],[166,231],[167,231],[168,231],[169,231],[170,231],[171,231],[172,231],[173,231],[174,231],[175,231],[176,231],[177,231],[178,231],[179,231],[180,231],[181,231],[182,231],[183,231],[184,231],[185,231],[186,231],[187,231],[188,231],[189,231],[190,231],[191,231],[192,231],[193,231],[194,231],[195,231],[196,231],[197,231],[198,231],[199,231],[200,231],[201,231],[202,231],[203,231],[204,231],[205,231],[206,231],[207,231],[208,231],[209,231],[210,231],[142,230],[143,230],[144,230],[145,230],[146,230],[147,230],[148,230],[149,230],[150,230],[151,230],[152,230],[153,230],[154,230],[155,230],[156,230],[157,230],[158,230],[159,230],[160,230],[161,230],[162,230],[163,230],[164,230],[165,230],[166,230],[167,230],[168,230],[169,230],[170,230],[171,230],[172,230],[173,230],[174,230],[175,230],[176,230],[177,230],[178,230],[179,230],[180,230],[181,230],[182,230],[183,230],[184,230],[185,230],[186,230],[187,230],[188,230],[189,230],[190,230],[191,230],[192,230],[193,230],[194,230],[195,230],[196,230],[197,230],[198,230],[199,230],[200,230],[201,230],[202,230],[203,230],[204,230],[205,230],[206,230],[207,230],[208,230],[209,230],[210,230],[142,229],[143,229],[144,229],[145,229],[146,229],[147,229],[148,229],[149,229],[150,229],[151,229],[152,229],[153,229],[154,229],[155,229],[156,229],[157,229],[158,229],[159,229],[160,229],[161,229],[162,229],[163,229],[164,229],[165,229],[166,229],[167,229],[168,229],[169,229],[170,229],[171,229],[172,229],[173,229],[174,229],[177,229],[178,229],[179,229],[180,229],[181,229],[182,229],[183,229],[184,229],[185,229],[186,229],[187,229],[194,229],[198,229],[199,229],[200,229],[201,229],[202,229],[203,229],[204,229],[205,229],[206,229],[207,229],[208,229],[209,229],[210,229],[142,228],[143,228],[144,228],[145,228],[146,228],[147,228],[148,228],[149,228],[150,228],[151,228],[152,228],[153,228],[154,228],[155,228],[156,228],[157,228],[158,228],[159,228],[160,228],[161,228],[162,228],[163,228],[164,228],[165,228],[166,228],[167,228],[168,228],[169,228],[170,228],[171,228],[177,228],[178,228],[179,228],[180,228],[181,228],[182,228],[183,228],[184,228],[185,228],[186,228],[187,228],[198,228],[199,228],[200,228],[201,228],[202,228],[203,228],[204,228],[205,228],[206,228],[207,228],[208,228],[209,228],[210,228],[142,227],[143,227],[144,227],[145,227],[146,227],[147,227],[148,227],[149,227],[150,227],[151,227],[152,227],[153,227],[154,227],[155,227],[156,227],[157,227],[158,227],[159,227],[160,227],[161,227],[162,227],[163,227],[164,227],[165,227],[166,227],[167,227],[173,227],[174,227],[175,227],[176,227],[177,227],[178,227],[179,227],[180,227],[181,227],[182,227],[183,227],[184,227],[185,227],[186,227],[187,227],[188,227],[189,227],[190,227],[191,227],[192,227],[193,227],[194,227],[195,227],[196,227],[197,227],[198,227],[199,227],[200,227],[201,227],[202,227],[203,227],[204,227],[205,227],[206,227],[207,227],[208,227],[209,227],[210,227],[249,227],[250,227],[251,227],[252,227],[253,227],[254,227],[255,227],[142,226],[143,226],[144,226],[145,226],[1
```

**Comment by Hypfer** [comment]
Hackishly fixed now.

Thanks for reporting
