### ISSUE TITLE
Latest docker image fails with npm error

### ISSUE THREAD

**Issue by NearlCrews** [Hypfer/ICantBelieveItsNotValetudo#27]
Hello,

The last update seemed to have broken something with icantbelieveitsnotvaletudo. Here's the error I'm getting on a clean docker start:

<details>
<summary>docker logs</summary>

```
docker logs icantbelieveitsnotvaletudo

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_12_48_629Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_12_53_772Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_12_54_834Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_13_00_089Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_13_02_541Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_13_05_997Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_13_11_353Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_13_26_231Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_13_39_869Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_14_06_282Z-debug.log

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /app/lib/MapDrawer.js
- /app/lib/MqttClient.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/app/lib/MapDrawer.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/MapDrawer.js', '/app/lib/MqttClient.js', '/app/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@0.3.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i-cant-believe-its-not-valetudo@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T14_14_58_316Z-debug.log
```

</details>

Let me know if you need any additional information.

**Comment by Hypfer** [comment]
Thank you for reporting.

Sorry. Webstorm moved half of the changes to a different changelist without me noticing which basically pushed a completely broken version to master.

Try again now

**Comment by NearlCrews** [comment]
I was just checking on dockerhub and it looks like the last update was 18 hours ago:
https://hub.docker.com/r/bruvv/icantbelieveitsnotvaletudo/tags

Does it need a new build on there too? I'm pulling it via docker compose:

```
version: "3.3"
services:
  icantbelieveitsnotvaletudo:
    image: bruvv/icantbelieveitsnotvaletudo
    restart: always
    container_name: icantbelieveitsnotvaletudo
    ports:
      - "3000:3000"
    volumes:
      - ${ROOT}/valetudo/config.json:/app/config.json
```

**Comment by NearlCrews** [comment]
...derp. I just realized that was a fork. I'll move the ticket over there. Feel free to close this. Sorry about that.

**Comment by Hypfer** [comment]
Probably since there's no official image on the docker hub.

`Pulls 50K+`

Thats a lot more than expected. Oh well.

I'd recommend building the image yourself using docker compose like this:

```
    icantbelieveitsnotvaletudo:
        build:
          context: ./ICantBelieveItsNotValetudo/
          dockerfile: Dockerfile
        container_name: "ICantBelieveItsNotValetudo"
        restart: always
        volumes:
            - /foo/bar/mylocalhost/config.json:/app/config.json
```

**Comment by NearlCrews** [comment]
Thanks much. Tried building it but getting another error:

```
Step 4/6 : RUN npm install
 ---> Running in 5bd4490f2b38

> canvas@2.6.1 install /app/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-musl-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.5.0 (node-v83 ABI, musl) (falling back to source compile with node-gyp)
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 5.4.44-2-pve
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/app/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /app/node_modules/canvas
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.44-2-pve
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /app/node_modules/canvas
node-pre-gyp ERR! node -v v14.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN i-cant-believe-its-not-valetudo@0.3.0 No description
npm WARN i-cant-believe-its-not-valetudo@0.3.0 No repository field.
npm WARN i-cant-believe-its-not-valetudo@0.3.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T15_39_17_556Z-debug.log
ERROR: Service 'icantbelieveitsnotvaletudo' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

I'm assuming it's related to the 404:
```
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-musl-x64.tar.gz
```

**Comment by Hypfer** [comment]
Oh. We can't use the alpine baseimage then.

I've updated the dockerfile. Try again now

**Comment by NearlCrews** [comment]
Fixed! Thanks much :).
