### ISSUE TITLE
Failed to start: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by sinegovsky-ivan** [Hypfer/ICantBelieveItsNotValetudo#39]
hello!
Im using this package with hass.io (docker container on Synology).
When i try to start package, im getting error: "SyntaxError: Unexpected token  in JSON at position 0"

My config:
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  scale: 4
  rotate: 0
mapColors:
  floor: '#0076ff'
  obstacle_weak: '#6699ff'
  obstacle_strong: '#52aeff'
  path: '#ffffff'
mqtt:
  identifier: rockrobo
  topicPrefix: valetudo
  autoconfPrefix: homeassistant
  broker_url: 'mqtt://--:----@192.168.31.250'
  caPath: ''
  mapDataTopic: valetudo/rockrobo/map_data
  minMillisecondsBetweenMapUpdates: 10000
  publishMapImage: true

My log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-config: executing... 
[14:05:48] INFO: Setup config
[cont-init.d] setup-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:05:48] INFO: Start ICantBelieveItsNotValetudo

> i-cant-believe-its-not-valetudo@0.3.0 start /app
> node app.js

Loading configuration file: /app/config.json
Connecting to MQTT Broker
Webserver running on port 3000
Connected to MQTT Broker
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:85:42)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:336:12)
    at work (/app/node_modules/mqtt/lib/client.js:292:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:85:42)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:336:12)
    at work (/app/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:334:11)

**Comment by Ramsei** [comment]
I have a similar problem, did you manage to deal with the error ?

**Comment by sinegovsky-ivan** [comment]
No. I just stop using this add-on.

**Comment by exotsk** [comment]
i have the same. valetudo mapper have the same error too

**Comment by Hypfer** [comment]
There is no official hassio add-on.
