### ISSUE TITLE
error while starting

### ISSUE THREAD

**Issue by GekoCH** [Hypfer/ICantBelieveItsNotValetudo#82]
I tried to start it with npm start then this was the output: Any adivce?
Installation did went well but starting...

```
/root/Icantbelieveitsnotvaletudo/lib/MqttClient.js:30
        this.caPath = options.caPath ?? "";
                                      ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/Icantbelieveitsnotvaletudo/app.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i-cant-believe-its-not-valetudo@2021.12.0 start: `node app.js`
npm ERR! Exit status 1
```

**Comment by GekoCH** [comment]
sorry I had the wrong NPM version...

**Comment by GekoCH** [comment]
close
